### ISSUE TITLE
Todo list for 01.11.2016

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#17]
Todo list
- [ ] Add premium ads #13 
- [ ] Add payment/credit cards #13 
- [ ] Make sketches for changing the design #15 
- [ ] Search for bugs and fix them, make comfort changes
- [ ] Couple of small changes #19
